# docker compose to launch tests

services:
  elasticsearch:
    image: elasticsearch:8.4.1
    environment:
      - discovery.type=single-node
    networks:
      - test
  tester:
    build: tester_env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - elasticsearch
    networks:
      - test

networks:
  test:
    driver: bridge